# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 789495bfd3d23c4b98b3f6f77f8d0005831f4610200b85b755e21ea065c171db1a096b86d7ce62deff8e6300bcf83b313f6eb87726ed992ca904b3d253b2636f

test:
  secret_key_base: b7fc6eca76588ca59f1f67fa01c264a2ddaed5e981fceaa50a44d9569084096d6b27ef83e821145699c1c93ba3d41ad90abfdd31d9c8ff6fe1abfc03a367f3c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
